server:
  port: 8080
  context: /test/hello
spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/marketcommander?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true