server:
  port: 8080
  context: /
spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marketcommander?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
    show-sql: true
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
